-- Keep all existing notifications.
-- userId becomes recipientId.

ALTER TABLE "Notification"
RENAME COLUMN "userId" TO "recipientId";


-- Optional sender: NULL means notification generated by the system.

ALTER TABLE "Notification"
ADD COLUMN "senderId" TEXT;


-- Rename existing index only.
ALTER INDEX IF EXISTS "Notification_userId_lu_idx"
RENAME TO "Notification_recipientId_lu_idx";


-- Add relation sender -> User
ALTER TABLE "Notification"
ADD CONSTRAINT "Notification_senderId_fkey"
FOREIGN KEY ("senderId")
REFERENCES "User"("id")
ON DELETE SET NULL
ON UPDATE CASCADE;


CREATE INDEX "Notification_senderId_idx"
ON "Notification"("senderId");